# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deputado', '0002_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
